import = ["~/.config/sesh/base.toml"]

[[session]]
name = "google-drive"
path = "~/Library/CloudStorage/GoogleDrive-ltfibonacci@gmail.com/My Drive"
startup_command = "ls -F"
windows = [ "shell", "llm", "vscode" ]

[[session]]
name = "equiquant"
path = "~/repos/equiquant/main"
windows = [ "shell", "llm", "vscode" ]

[[session]]
name = "fibonacci"
path = "~"
windows = [ "remote-shell", "remote-llm", "cloud-lab" ]

[[window]]
name = "remote-shell"
startup_script = "ssh fibonacci"

[[window]]
name = "remote-llm"
startup_script = "ssh -t fibonacci \"llm\""

[[window]]
name = "remote-vscode"
startup_script = "code --remote ssh-remote+fibonacci ~ && exit"

[[window]]
name = "cloud-lab"
startup_script = "code ~/repos/cloud-lab/cloud-lab.code-workspace && exit"
