import = ["~/.config/sesh/base.toml"]

[[session]]
name = "platform-security-team"
path = "~/repos/platform-security-team"
startup_command = "git pull"
preview_command = "ls ~/repos/platform-security-team"
windows = [ "shell", "llm", "vscode" ]

[[session]]
name = "platform-security-terraform"
path = "~/repos/platform-security-terraform"
startup_command = "git pull"
preview_command = "ls ~/repos/platform-security-terraform"
windows = [ "shell", "llm", "vscode" ]
